### ISSUE TITLE
Prep 3:Continous Variable cannot be mapped to shape

### ISSUE THREAD

**Issue by debit7** [gvsu-sta518/community#14]
I tried to do Exercise 1 given in **Preparation3**.The first 2 plots they worked nicely but while mapping *cty to Shape* .
The following error occurs as shown in the picture.

<img width="952" alt="Screen Shot 2021-09-12 at 11 58 25 PM" src="https://user-images.githubusercontent.com/20457939/133096401-e731535f-8f4a-4ec5-a907-ed98e8ec114c.png">

**Comment by asimot** [comment]
I believe this is what we were trying to see in the example, that a continuous variable cannot be used with the shape aesthetic.  

Recall that shape can only discriminant between 6 different shapes by default, thus a continuous variable such as city miles per gallon (cty) would easily have more than 6 unique categories.

**Comment by lindsaybandyk** [comment]
> I tried to do Exercise 1 given in **Preparation3**.The first 2 plots they worked nicely but while mapping _cty to Shape_ .
> The following error occurs as shown in the picture.
> 
> <img alt="Screen Shot 2021-09-12 at 11 58 25 PM" width="952" src="https://user-images.githubusercontent.com/20457939/133096401-e731535f-8f4a-4ec5-a907-ed98e8ec114c.png">

the correct answer would be if you are replacing the "cty" next to shape, size, and colour would be putting in the word class instead. We are defining the class which is a change of aesthetics, meaning.. ",shape=class" ",size=class" and the same for color (or colour)
