### ISSUE TITLE
Making Commits

### ISSUE THREAD

**Issue by elaynast** [gvsu-sta518/community#17]
I still don't think that I'm understand the whole knit, stage, and commit process. I don't understand what each aspect is and I don't think that most of my commits are going anywhere. Am I supposed to push when I commit? Can someone explain this process again?

**Comment by dykesb** [comment]
I'm going to attempt to provide more details as to what each of these steps are doing:
- **Pre-knit**: You are typing in plain text (markdown and R code chunks) working on part of a document (say the exploratory data section for a report) and you have made some good progress where you wish to see how everything looks.
- **Knit**: This takes your plain text file (`.Rmd`) and renders the information into a single document (we've been doing GitHub `.md` files, but this could also be a Word document, webpage, or PDF) that interweaves your prose, code, and output. Knitting actually creates many new documents from your original `.Rmd` file. If your report creates graphs or other images, these are also created and saved into a folder. The knitted document is shown in the pop-up window for you to review your work. Each time you knit, this saves your work to your RStudio session - your current version is only available to you in RStudio. However, if you want to share this with others (or even future you), you need to send it all files to GitHub.
-  **Stage**: This is done in the **Git** pane by checking the box next to each item you wish to send to GitHub. Typically, this will means checking the box for every item listed here (there might be times where you don't want to do this and we can talk about that later). Staging an item is indicating to Git (the language that communicates between RStudio and GitHub) that you want to send these files to GitHub.
- **Commit**: This provides an opportunity to add more detail about the changes you made and why you made them. Think of this as adding a sticky note of information to a document. Committing includes adding a commit message and actually committing the work. Clicking on the commit button in GitHub is applying the sticky note to your RStudio version, but it doesn't send it to GitHub yet. I try to do commits after I have finished a section before I move on to a different area of a project.
- **Push**: This is when you actually send your changes to GitHub. You do not need to push after every commit, but you should push before you "log off" for the session.
