### ISSUE TITLE
Editing columns/values in a matrix: activity 03

### ISSUE THREAD

**Issue by damosack** [gvsu-sta518/community#19]
I'm working through activity 03, where you need to manipulate the top_secret matrix in a few ways, and after searching online in every way I can think to, I'm still unsure how to (for example) subtract even numbers from every value in the first column while still preserving the *other* columns in the matrix.

Below is the best I could come up with (top_secret4 is my name for the vector produced after the first four steps), but this sequence of code produces a vector named step 7 with only 1 column of the original matrix. Which is obviously not ideal, since we basically want an edited version of tsmatrix, where column one has been modified, and the other four are preserved.

```{r}
tsmatrix<- matrix(data=top_secret4, ncol = 5)
evens <- seq(2, 502, 2)
step7 <- ts[,1] - evens
```

**Comment by ian-curtis** [comment]
I think you are on the right track!!

Mine looks like this (and it seems to work)
```
# Create Matrix with 5 Columns
secret_matrix <- matrix(data = top_secret, ncol = 5)
# Generate Evens between 2 and 502
evens = seq(2, 503, 2)
# Edit First Column of Matrix
secret_matrix[,1] <- secret_matrix[,1] - evens
```
Basically in that last step, I'm saying take the first column of the matrix, subtract the events, and then overwrite the existing column with my modified column. This leaves the other columns untouched but keeps them in the matrix. 

However, if I am not mistaken,  you could just add a line to your code: `tsmatrix[,1] <- step7` which **I think** would take your single vector of `step7` and overwrite the first column of your matrix.

**Comment by damosack** [comment]
Thanks Ian! That makes much more sense, and I don't think I'd have figured that one out myself
