### ISSUE TITLE
Error initiating session for external requests. 

### ISSUE THREAD

**Issue by debit7** [gvsu-sta518/community#21]
I was doing preparation4. In the first part while loading the library I encountered the error. Does anybody have the same problem and fixes?
<img width="975" alt="Screen Shot 2021-09-20 at 9 04 58 PM" src="https://user-images.githubusercontent.com/20457939/134097146-9d96af2a-4092-484e-b01b-8233016b30e5.png">

**Comment by dykesb** [comment]
I think this is a server issue with RStudio. If you see something like this, refresh your screen. Other students have also said they were successful once they created a free RStudio account.
