### ISSUE TITLE
Activity 5 Questions

### ISSUE THREAD

**Issue by ferkullj** [gvsu-sta518/community#27]
I'm thinking my major boxplot is not looking how it's intended to. Can I clean up my x-axis or use jitter differently?
![image](https://user-images.githubusercontent.com/89871886/135547175-33903625-634f-4a01-b57d-0da7c369c56b.png)
![image](https://user-images.githubusercontent.com/89871886/135547303-9ea4e220-75ec-46a1-aa30-9eb8bab87653.png)

For category rankings, I believe my code and output makes sense. However, I'm not sure what the rankings are supposed to be. Is it just taking the values I created and ranking them from highest to lowest?
![image](https://user-images.githubusercontent.com/89871886/135547510-765252b5-4359-44f8-ad65-d29f22899485.png)
![image](https://user-images.githubusercontent.com/89871886/135547570-ebe5d02c-766f-416e-8596-7b9f0fde7231.png)

**Comment by dykesb** [comment]
For commenting and future searchability, it would be helpful if you kept each issue to a unique question. Could you split this up and provide a unique Issue name for each question you are asking here?
