### ISSUE TITLE
Activity 5: Ranks Question

### ISSUE THREAD

**Issue by ferkullj** [gvsu-sta518/community#29]
For category rankings, I believe my code and output makes sense. However, I'm not sure what the rankings are supposed to be. Is it just taking the values I created and ranking them from highest to lowest?
![image](https://user-images.githubusercontent.com/89871886/135547510-765252b5-4359-44f8-ad65-d29f22899485.png)
![image](https://user-images.githubusercontent.com/89871886/135547570-ebe5d02c-766f-416e-8596-7b9f0fde7231.png)

**Comment by dykesb** [comment]
Remember that you can type `?rank` in your **Console** to see what the function is doing, but your thought is correct! `rank` takes a vector/variable-column and returns the rank order position. So, the ranks of the vector `c(14, 77, 4, 11)` (i.e., `rank(c(14, 77, 4, 11))`) would be `c(3, 4, 1, 2)`. The number `4` is the lowest value so it gets a rank of `1`; the number `77` is the highest value, so it gets a rank of `4`.
