### ISSUE TITLE
`str_split` vs. `str_extract_all`

### ISSUE THREAD

**Issue by ian-curtis** [gvsu-sta518/community#36]
Hi all!

I am working on Activity 8 (the `strings.rmd` file) and I am stuck on the part asking us to use `str_extract_all` to separate collaborating artists by "," or "&". I was able to get it to work by using the code below:

```
collab_artist <- artist_credentials %>% 
  str_replace_all(" featuring.*| feat.*", "") %>% 
  str_split(pattern = ", | \\& | with ") %>% 
  unlist() %>% 
  str_trim(side = c("both"))
```

I added "with" because some artists describe collaboration by "with". As I said, this worked and all was fine until I arranged the collaborating artists by frequency. That's when I discovered that "His Orchestra" was in the top three which indicates that R separated the actual artist from the "& His Orchestra" (such as Glenn Miller and His Orchestra). Did anyone figure out how to use `str_extract_all` with this problem and did you get this same occurrence?

**Comment by dykesb** [comment]
For your main question, I used `str_extract_all("[^,&]+")` - extract/keep any characters that are not one of `,` or `&` (including multiples).

You could definitely improve this process a lot to make sure you get full band names. You could look into a [negative lookahead](https://stackoverflow.com/questions/1240275/how-to-negate-specific-word-in-regex), for example, to keep "Glenn Miller & His Orchestra" together. There could be an entire course on regular expression so I am not expecting everyone to know all of these. How much you need to know really depends on the individual and what they hope to apply their coding background to. 

Keep in mind, STA 418/518 is an R course not a Python, regular expression, SAS, ... course. Pulling out simple patterns should be enough for our uses.
