### ISSUE TITLE
Scrape URL with more than one table

### ISSUE THREAD

**Issue by asimot** [gvsu-sta518/community#46]
Trying to scrape Player Standard Batting table at [here](https://www.baseball-reference.com/leagues/majors/2020-standard-batting.shtml).  The second table is not being read and cannot be scraped, but the first table, Teams Standard Batting is able to be extracted.

**Comment by BryanJacques** [comment]
Do you have an example of the code you're using?

**Comment by asimot** [comment]
> Do you have an example of the code you're using?
Tried elements 'table' and by ID, as well as using the xpath for the table desired and CSS, to which none worked.

`testurl <- "https://www.baseball-reference.com/leagues/majors/2020-standard-batting.shtml"

a <- testurl %>%
  #retrieve elements with table in HTML
  read_html() %>%
  html_elements(".table_wrapper") %>%
  html_table()
  #paste0()
  #html_elements("table") 
  #html_elements(xpath = "//*[@id=\"players_standard_batting\"]") %>%
  #create a table from HTML`
