### ISSUE TITLE
Day 18 Agenda

### ISSUE THREAD

**Issue by ferkullj** [gvsu-sta518/community#52]
Is bootstrapping generally more or less accurate in estimating population parameters than when taking multiple samples? Would there be a reason to use bootstrapping besides only having 1 sample?

**Comment by LeviRosendall** [comment]
I get the process of bootstrapping, but it seems to keep the same mean and just produce as confidence interval. Is it possible that this would still cause problems if your sample is not a good representation of the population?

**Comment by nash-meg** [comment]
I was thinking similarly to Levi regarding a good representation. In the example, they sampled only 50 pennies from one bank across all of America. What if banks in Idaho or Texas have a noticeably higher number of older or newer pennies?

**Comment by elaynast** [comment]
@ferkullj I would imagine that it is less accurate in making inferences about the population than taking multiple samples. I agree with what Meghan said in that different banks could have different amounts of older or newer pennies, so this probably would not be as applicable to the entire population of banks than taking samples from different banks in America.
