### ISSUE TITLE
Day 19 Agenda

### ISSUE THREAD

**Issue by lcadagin** [gvsu-sta518/community#53]
There was no Day 19 Agenda Issue, so I created this one.

The muddiest this about this preparation was what Output functions in the Shiny UI matched up with what Render functions in the Shiny Server.

For example, is plotOutput() always paired with renderPlot() or are there other render functions that could be used with plotOutput()?

**Comment by elaynast** [comment]
I think I'm having the same confusion as Luke. I don't think I fully understand what the renderPlot() function is doing and how to pick which Render function I need. In module one it was obvious since we were using ggplot, but I don't think I'll understand which to use when I'm not plotting something.

**Comment by manapradit** [comment]
The muddiest thing for me is to fix the activity "1-3 Fix it up". The graph did not show after fixing and running the code. Then, I realized that the uppercase matters. I got the final graph after changing scatterplot to scatterPlot.

**Comment by manapradit** [comment]
The muddiest thing for me is to fix the code in the activity "1-3 Fix it up". The graph did not show after running the code. Then, I realized that the uppercase matters. I got the final graph after changing scatterplot to scatterPlot.

**Comment by dykesb** [comment]
@lcadagin, @elaynast, et al: it is a little hard to instantly see the relations here, but the "Outputs" section of the RStudio Shiny Cheatsheet (https://github.com/rstudio/cheatsheets/blob/main/shiny.pdf) has the typical pairings of render* -> *Output in the same "row" (notice that renderPrint and verbatimTextOutput differ with their syntax-pairing and renderUI has two options: uiOutput or htmlOutput). These are the typical outputs, but there are many being developed by the community: http://gallery.htmlwidgets.org/ or http://www.htmlwidgets.org/showcase_leaflet.html.

**Comment by keydels** [comment]
I was also a little confused on how to decide which render function to use. In the module it made sense since we were being walked through everything, but if I were to do this on my own I think I would be super lost.
