### ISSUE TITLE
Getting pdf Table into R

### ISSUE THREAD

**Issue by ferkullj** [gvsu-sta518/community#57]
From an article Bradford pointed me towards, it looks like the most popular way to convert a pdf data table to an R data frame was with a package called tabulizer, but it looks like that package got taken down from CRAN. I've tried the following so far instead:
```{r getting variable code descriptions from pdf}
#install.packages("Rcpp")
library(Rcpp)
#install.packages("pdftools")
library(pdftools)

download.file("https://www.cpsc.gov/s3fs-public/2019_NEISS_Coding_Manual.pdf", "product_codes.pdf", mode = "w")

#product_codes <- pdf_text("product_codes.pdf")
product_data <- pdf_data("product_codes.pdf")
text_analysis <- as.data.frame(product_data[175])

text_values <- text_analysis %>% 
  select(-c("width", "height", "x", "y", "space")) %>%
  slice(21:233) %>% 
  pull(text)
unlist(str_split(text_values, " ,"))
```
Part of the output from above is here:
![image](https://user-images.githubusercontent.com/89871886/141390170-b8c0c633-1d64-43f0-8a82-0e066033b365.png)

To interpret this, "0102" is the product code for "Wringer washing machines" and so on. Is there a way for me to split this up so the 4 digit product code is one column of a data frame and the product name is the other column? I was thinking I could split when the characters change from digit to alphabetic but I'm not sure how to accomplish that.

**Comment by dykesb** [comment]
First, thanks for the repex (reproducible example)!!! Remember to include `library(dplyr)` (or `tidyverse`) as you are using the pipe and some other functions from there.

This will get you a list where each item is a vector for the products. The product names are still being separate strings, but you could write a function that concatenates (i.e., using `paste`) the second through last value in each vector. Then you could convert/coerce the list to a data frame/tibble (e.g., `as.data.frame`):

```
split(text_values, cumsum(str_detect(text_values, "[:digit:]")))
```

```
List of 47
 $ 1 : chr [1:4] "0102" "Wringer" "washing" "machines"
 $ 2 : chr [1:6] "0106" "Electric" "clothes" "dryers" ...
 $ 3 : chr [1:6] "0107" "Gas" "clothes" "dryers" ...
 $ 4 : chr [1:4] "0110" "Electric" "heating" "pads"
 $ 5 : chr [1:5] "0112" "Sewing" "machines" "or" ...
```

This is creating groups based on whenever an entry contains a digit (`cumsum(str_detect(...))`), then creating a new vector for each group (`split`).

Google Search: "split a vector into multiple vectors based on first occurrence"
Reference for inspiration: https://stackoverflow.com/questions/25411653/how-do-i-split-a-vector-into-a-list-of-vectors-when-a-condition-is-met
