### ISSUE TITLE
Working with .csv in Shiny

### ISSUE THREAD

**Issue by ferkullj** [gvsu-sta518/community#58]
Is there a way to read in our data as .csv for Shiny or convert it to .RData? Our modules used .RData and I can't get my app to even begin using .csv. I've tried having the user upload their own .csv successfully, but my file was too big for this method to work.

**Comment by dykesb** [comment]
In the modules, the folder structure was:

```
+ app-folder
  + app.R
  + data.RData
```

Then, the beginning of the `app.R` file begins with:

```
library(shiny)
load("data.RData")
```

Then, you refer to `data`  to use the loaded data.

For CSV files, you would do something similar, but using different functions:

```
+ app-folder
  + app.R
  + data.csv
```

And the beginning of the `app.R` file being (note that I am not loading the tidyverse):

```
library(shiny)
obj_name <- readr::read_csv("data.csv")
```

Then, refer to `obj_name` to use the data.
