### ISSUE TITLE
Using a Manipulated Form of Data in Shiny

### ISSUE THREAD

**Issue by ferkullj** [gvsu-sta518/community#59]
I've been confused on when/where to include my edited data set in Shiny. For example, in my .Rmd file I have edited a few variables and plan to add labels to the original data set, but in my Shiny app.R file, I just have the basic data loaded in. Should the code with pipes, mutates, etc. be copied to my Shiny app? Or would it make more sense to download an edited file of my data once I've manipulated everything and have that be the data set I use in Shiny?

Let me know if that didn't make any sense.

**Comment by dykesb** [comment]
Depends on how frequent these new variables need to be created. My guess is that they are calculated once, then used throughout your app. In this case, you would do this at the starts of your `app.R` (i.e., after you load your packages and data). If these need to be calculated many times, it would probably need to be done in the server-side of things.
