### ISSUE TITLE
Final Project and Self-Reflection

### ISSUE THREAD

**Issue by dykesb** [gvsu-sta518/community#60]
I wanted to summarize our discussion from class regarding the final project and final self-reflection.
- You will present your final Data Project on Dec. 9 or Dec. 16 (for Section 01 - TR@8:30am) or on Dec. 8 or Dec. 13 (for Section 02 - MW@6:00pm). I will randomize the presentation schedule for the two dates on Dec. 1/2 during class (I will need to know how you plan to present on this date).
- Your final self-reflection can be turned in by Friday, Dec. 3 at 5pm to receive feedback and be able to revise and resubmit. The official due date for this is Thursday, Dec. 16 by 5 pm.

**Comment by sarbauprety** [comment]
Do we need to turn in the activities as well for our final self-reflection?

**Comment by dykesb** [comment]
Activities are not collected. These would essentially be my notes were this a traditional, lecture-driven course.
