### ISSUE TITLE
Working With Clustered Bar Chart in ggplot

### ISSUE THREAD

**Issue by ferkullj** [gvsu-sta518/community#61]
I'm trying to customize a clustered bar chart but it's proving to be finicky compared to a "regular" ggplot bar chart. I have data in long form that looks like this:
<img width="402" alt="image" src="https://user-images.githubusercontent.com/89871886/142776528-5d756a0c-27f4-4749-940b-1f2dbc8b38dd.png">
I am ok with my first plot but would like to change some aspects:
```{r}
diff2 %>%
  head() %>% 
  ggplot(aes(fill = Cleaning_Status, y = Contaminated_Bikes, x = station_name))+
  geom_bar(position="dodge", stat="identity", width = .66)+
  labs(title = "Contaminated Bikes Per Station\n in Cleaned vs. Not Cleaned State", x = "Station Name", y = "Contamined Bikes", fill = "Cleaning Status")+
  coord_flip()
```
<img width="436" alt="image" src="https://user-images.githubusercontent.com/89871886/142776585-ff435bc6-d324-4b62-b0f9-3e061c6354df.png">
I would like to first arrange the data by contamination number per station( i.e. show the top 5 contaminated stations while keeping the cleaned and not cleaned station observations together). I cannot seem to keep the stations together when I arrange by contamination. I've tried:

```{r}
diff2 %>%
  arrange(desc(Contaminated_Bikes, station_name))
```
and things like that but it doesn't do what I'm expecting/wanting.
Lastly, I would like to change(manually pick) the color by cleaning status, but I've tried many "color =" and "fill =" options in different places and I cannot seem to get it. Am I missing some obvious option in my original code?

**Comment by dykesb** [comment]
I wonder if `[fct_reorder](https://forcats.tidyverse.org/reference/fct_reorder.html)` would be able to help with the specific bar ordering. However, counts of might be somewhat misleading (e.g., the "cleaned" bikes for the second station in your plot is a much high proportion of all bikes at that station compared to the other stations). A [percent stacked](https://www.r-graph-gallery.com/48-grouped-barplot-with-ggplot2.html#percent-stacked-barchart) might be more informative (and perhaps easier to reorder).

For manual colors, the [Colors](http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/) section of the *Cookbook for R* by Winston Chang could be a good place to start.
