### ISSUE TITLE
Shiny app reloading data each time.

### ISSUE THREAD

**Issue by ian-curtis** [gvsu-sta518/community#62]
We are having to create our own dataset by access the Spotify API. As such, the data set is getting very large, very fast and will continue to get larger. Right now, our shiny app loads our data like so
```
my_files <- list.files(path=here::here("data/"), pattern="*.csv", full.names = TRUE)
big_spotify <- read_csv(my_files)
big_spotify <- big_spotify %>% 
  mutate(year = substr(release_date, 1, 4),
         duration_s = as.duration(duration) / 1000)
spotify_nodup <- big_spotify %>% 
  distinct(track_uri, .keep_all = TRUE)
spotify_nodup <- spotify_nodup[-20]
```
where we grab all files ending in `.csv`, combine them into one tibble, create a couple variables, and remove duplicates and an empty column. This process already takes some time and will take longer as we add more data.

Every time we hit "Run App", the app has to reload the entire dataset. We would like the app to load the data once and then just use it for the rest of the session. Is there a better way to call in large datasets quickly to a shiny app? Is there a way to put in a "please wait" message while the data loads (even though it loads outside of the `ui` and `server`?

**Comment by dykesb** [comment]
As you are testing, you could work with a smaller randomly selected subset. 

Sections 15.2.2 and 15.3 of [Engineering Production-Grade Shiny Apps](https://engineering-shiny.org/common-app-caveats.html#using-external-databases) by Fay, Rochette, Guyader, and Girard discuss external dataset options. The RStudio Community also has some [similar suggestions](https://community.rstudio.com/t/handle-big-data-in-r/5175)

**Comment by ian-curtis** [comment]
We explored `{feather}` a little bit and it will have to work for now. Do you have good resources for adding data to a database and connecting it with Shiny?

**Comment by ian-curtis** [comment]
(Somewhat easy to read, perhaps?) Some of the things I have found and that your sources link too are a lot to take in.

**Comment by dykesb** [comment]
Setting up databases is beyond the scope of this course (and my current ability). This example shows how to create an on-disk database: https://data.library.virginia.edu/creating-a-sqlite-database-for-use-with-r. For remote access, you will need to do more digging. Note that they recommend using an API, if available (which you do have, but probably drastically changes your app code).
