### ISSUE TITLE
Predictive search/dropdown menu in Shiny `server`

### ISSUE THREAD

**Issue by ian-curtis** [gvsu-sta518/community#63]
Right now, we have a basic shell for a Shiny app. One of the `ui` pieces is a text input:
```
textInput(
        inputId = "artist",
        label = "Search for an artist"
      )
```
which allows users to search for an artist (we also have a generate button so that the output will not run until the button is pushed). We would like to have a feature where options will pop up as someone types something since 
1. Some artist names are spelled differently (P!nk vs. Pink, Kesha vs. Ke$ha)
2. Right now, users have to type an *exact match* to an artist name (this includes their entire name, case sensitive, and with special characters)
3. Users can only search for artists they know and won't be able to find other artists.

We have messed around with `selectize` and `selectizeInput`, but there are way too many artists for selectize to work; the app just lags like crazy and usually leads to R needing to be restarted. We really are just looking for simple predictive text that provides all artists that meet the criteria that a user has already typed.

On a very related note: is there a way to not differentiate between special characters? For instance, if someone searches for "Céline Dion" OR "Celine Dion" we want the data for her music to show up. With `textInput`, only exact matches will work. Not everyone has special characters on their computer, especially when it comes to Chinese, Thai, etc. characters.

**Comment by dykesb** [comment]
I would think that [`selectizeInput`](https://shiny.rstudio.com/articles/selectize.html) would be the way to go, but there look to be some ways to speed this up: https://stackoverflow.com/questions/38438920/shiny-selectinput-very-slow-on-larger-data-15-000-entries-in-browser
