### ISSUE TITLE
self reflection 

### ISSUE THREAD

**Issue by vinaybommireddy** [gvsu-sta518/community#65]
I'm a bit confused about the submission of self-reflection. I wanted to know if we need to submit a word doc or .rmd file for submission. Also, do we need to submit our project code along with self-reflection?

**Comment by dykesb** [comment]
What you turn in for your self-reflection will vary from individual-to-individual. This can be a Word document or an Rmd file knitted to some viewable output (I will not be able to review an Rmd file by itself, you must knit it to something - a Word doc, PDF, webpage on your personal site, etc.), video, webcomic, portfolio, personal website, etc.

In the Final Self-Reflection directions, it states to provide me with a URL to your final project product (the paper,  shiny app hosted on shinyapps.io, or other "thing" that is the deliverable of your final project) **and** a URL to the GitHub repo containing all of your code.
