### ISSUE TITLE
R-studio to Github push error 

### ISSUE THREAD

**Issue by saminturi97** [gvsu-sta518/community#66]
I am unable to push the changes that are done in R-studio to get hub I have attached the screen shot of the error below can you please help me with this?
![Github_error](https://user-images.githubusercontent.com/89869669/144477528-b3e3e6be-fe8a-4cb7-be27-0ea114cc61e7.png)

**Comment by dykesb** [comment]
Did you pull before pushing?

**Comment by saminturi97** [comment]
I just did the commit operation

**Comment by dykesb** [comment]
Did you get an error when you pulled? Were there merge conflicts in any of your files (e.g., the md file)?

**Comment by saminturi97** [comment]
no I did not get an error whin I pulled but I downloaded all the files in that R studio repo and created a new repo in GitHub placed the all the files I downloaded and then open this repo in R studio I able to push changes now.
