### ISSUE TITLE
Issue getting shiny app to run 

### ISSUE THREAD

**Issue by arepesh** [gvsu-sta518/community#68]
So I am trying to get a map to show up in a shiny app but I keep getting this error:
Listening on http://127.0.0.1:5012
Warning: Error in polygonData.default: Don't know how to get path data from object of class data.frame
  [No stack trace available]
Warning: Error in [.data.frame: undefined columns selected
  [No stack trace available]

I've tried googling the error but can't seem to get a straight answer. I think it has some issue with the merging of the original dataset and the shapefile but I'm just unsure on how to fix the problem.

**Comment by dykesb** [comment]
Are all of your datasets in your app folder? It looks like the issue is with a map data file. This would be easier to assist with more information.
