### ISSUE TITLE
Chi-Square Post Hoc Test in R

### ISSUE THREAD

**Issue by ferkullj** [gvsu-sta518/community#69]
Is there a good, current post hoc function to use in R? I'm using the chisq.test() function to run a Chi-Square analysis smoothly, but I would also like to do post hoc analysis with it. Most of the packages I'm finding won't install correctly or were taken from CRAN at some point. I'm having trouble with the one I did install.
```{r}
table(alc$Fire, alc$Alcohol)
chisq.test(alc$Fire, alc$Alcohol, correct = FALSE)

M <- as.table(rbind(alc$Fire, alc$Alcohol))
dimnames(M) <- list(Fire = alc$Fire, Alcohol = alc$Alcohol)
chisq.posthoc.test(M)
```
M needs to be a matrix and I'm not sure how to get it that way for this function. I get "Error in dimnames(M) <- list(Fire = alc$Fire, Alcohol = alc$Alcohol) : 
  length of 'dimnames' [1] not equal to array extent"

**Comment by dykesb** [comment]
Do you mean something like, "all pairwise difference in proportions ht/ci" when you say *chi square post hoc analysis*? Or, what package is `chisq.posthoc.test` from? 

To coerce an object that has the same type of variables in all columns to a matrix, you would use `as.matrix`.

**Comment by ferkullj** [comment]
Yes, that is what I mean. chisq.posthoc.test is the name of the function and the package.

**Comment by dykesb** [comment]
For `chisq.posthoc.test`, it takes a matrix/table of summarized values (i.e., the contingency/two-way table of counts). It looks like you are passing the raw columns of individual values, not summarized counts.

**Comment by ferkullj** [comment]
Thank you. The code below worked, but is there a faster way to accomplish that?
```{r}
#chisq test
table(alc$Fire, alc$Alcohol)
chisq.test(alc$Fire, alc$Alcohol, correct = FALSE)
#post hoc
fcount <- alc %>%
  group_by(Fire) %>% 
  summarize(n=n())

acount <- alc %>%
  group_by(Alcohol) %>%
  summarize(n=n())

M <- as.table(rbind(fcount$n, acount$n))
dimnames(M) <- list(Fire = fcount$Fire, Alcohol = acount$Alcohol)
chisq.posthoc.test(M, method = "bonferroni")
```

**Comment by dykesb** [comment]
`chisq.test` can take a matrix/table as well for the `x` argument so you could create this object once and use multiple times. Also, don't `table(...)` and your `rbind(...)` output producing essentially the same information?
