### ISSUE TITLE
Preparation 1 Task 2

### ISSUE THREAD

**Issue by sarbauprety** [gvsu-sta518/community#7]
I am a bit confused about Task 2 where it mentions "Create a Pull Request to your main branch from your new branch". Should I include the gif in my reflection?

**Comment by dykesb** [comment]
For creating a pull request, remember that this is covered around the 7 minute mark in Video 2.

Your gif should be added in the `README.md` file on the branch you created in your `preparation01` repo at the beginning of this task.

**Comment by sarbauprety** [comment]
That helps. Thank you!
