### ISSUE TITLE
Extracting User Selected Columns in Shiny

### ISSUE THREAD

**Issue by ferkullj** [gvsu-sta518/community#70]
I'm trying to use user selected variables to extract columns from a dataset called "square" in my Shiny app. The Id's for the selected variables are "var1" and "var2". I tried something in the first part of the below code, but obviously R didn't like the double $ signs. Putting parentheses around "input$var1" didn't help. The second part of the code is what I could think of, but that didn't work either. Is there a way to do this?

```{r}
output$freq <- renderPrint({
      table(square$input$var1, square$input$var1)
    })

output$freq <- renderPrint({
      var1 = as.character(input$var1)
      var2 = as.character(input$var2)
      table(square$var1, square$var2)
    })
```
My ideal output is simply:
<img width="125" alt="image" src="https://user-images.githubusercontent.com/89871886/144762141-8c249de4-33a8-47a7-9bca-104611bff0d6.png">

**Comment by dykesb** [comment]
This is doing a univariate bar graph, but I think this is essentially what you are trying to do with using base R `table`: https://shiny.rstudio.com/gallery/telephones-by-region.html

"Region" are the different columns in the `datasets::WorldPhones` dataset.

**Comment by ferkullj** [comment]
My shiny output worked before if I selected the variables myself, but it's not working as intended when I switch to the user selecting the variables still.
### Before:
```{r}
output$freq <- renderPrint({
      table(neiss$Fire, neiss$Alcohol)
    })
    
    output$chi_test <- renderPrint({
      chisq.test(neiss$Fire, neiss$Alcohol, correct = FALSE)
    })
```
<img width="256" alt="image" src="https://user-images.githubusercontent.com/89871886/144874360-340e10ce-a7e7-419e-a2d4-20fcef816620.png">

### Now:
```{r}
output$freq <- renderPrint({
      table(neiss[,input$var1], neiss[,input$var2])
    })
    
    output$chi_test <- renderPrint({
      chisq.test(neiss[,input$var1], neiss[,input$var2], correct = FALSE)
    })
```
<img width="298" alt="image" src="https://user-images.githubusercontent.com/89871886/144874123-309955e7-4bd3-4b3c-a7c2-ca57545d7fa8.png">

**Comment by dykesb** [comment]
It might be how your input selection is being done. Currently it looks like the app is selecting values of a variable (i.e., either no or yes and either male, female, or not recorded), not the variable itself (e.g., `Fire` or `Alcohol`). Based on that, I think you need to make a change in the UI-side.
