### ISSUE TITLE
Error Publishing Shiny App

### ISSUE THREAD

**Issue by ferkullj** [gvsu-sta518/community#72]
I've tried publishing my app using both:

> library(rsconnect)
> rsconnect::deployApp('~/STA 518/STA518_FinalProject/NEISS_2020_Data')

and then manually clicking the blue Publish button in the top right of the code panel.

Both times I got:
Error: Unhandled Exception: Child Task 1063079936 error: Unhandled Exception: HTTP 500: Internal Server Error
In addition: Warning messages:
1: In sprintf(gettext(fmt, domain = domain), ...) :
  one argument not used by format 'invalid uid value replaced by that for user 'nobody''
2: invalid uid value replaced by that for user 'nobody' 
3: In sprintf(gettext(fmt, domain = domain), ...) :
  one argument not used by format 'invalid gid value replaced by that for user 'nobody''
4: invalid gid value replaced by that for user 'nobody' 

My app does show up on my shinyapps.io account, but the status is Undeployed and the url doesn't work. Is there a fix to this or is it possible their servers are down currently?

**Comment by ian-curtis** [comment]
Accidentally created a duplicate issue earlier. I am also having this problem and am getting the same error but I don't think I have any warnings. It must be their servers? I know that Amazon Web Services went down today so maybe it's linked to that.

**Comment by dykesb** [comment]
Yup, I think this is due to AWS services being down: https://twitter.com/lisalendway/status/1468277402606489600?t=4wVER5E_Y1kUlDnIG4yA-Q&s=19

**Comment by ferkullj** [comment]
It's online now and everything is fine on my end!
