### ISSUE TITLE
"Please tell me who your are." pop-up in RStudio

### ISSUE THREAD

**Issue by dykesb** [gvsu-sta518/community#8]
![Screenshot (29)](https://user-images.githubusercontent.com/89947557/132543184-4d5d0f3b-cebf-48db-8a47-558095eb29a1.png)
 it is showing this error message while doing commit and it is not showing my file even though i tried pushing the file. what should i do?

_Originally posted by @ravichag in https://github.com/gvsu-sta518/community/issues/5#issuecomment-915363493_

**Comment by dykesb** [comment]
See [keydels](https://github.com/gvsu-sta518/community/issues/6#issuecomment-913843725) response.

**Comment by ravichag** [comment]
@dykesb Thank you professor. It worked.
