### ISSUE TITLE
remote: Permission to gvsu-sta518/{repo} denied to {username}

### ISSUE THREAD

**Issue by dykesb** [gvsu-sta518/community#9]
<img width="1280" alt="Screen Shot 2021-09-08 at 12 26 17 PM" src="https://user-images.githubusercontent.com/89804948/132547941-f6a3a603-dcc6-49e6-b2ee-24aec7e76189.png">

I seriously haven't a clue. First my R file did not show, so I created a new token. Then this started to pop up instead.

_Originally posted by @Luttrell6048 in https://github.com/gvsu-sta518/community/issues/5#issuecomment-915390164_

**Comment by dykesb** [comment]
It looks like you are trying to pull in *my* Preparation 2 repo (`gvsu-sta518/preparation02`), not *your* repo (`Luttrell6048/preparation02`). Make sure you forked my repo to your GitHub space first, then clone your copy of my repo to RStduio.

**Comment by Luttrell6048** [comment]
I was forked earlier, would I need to redo that as well?

**Comment by dykesb** [comment]
If your repo still exists (i.e., you did not delete it by going into Settings > Danger Zone > Delete Repo), you do not need to re-fork. To see your repos, click on your profile image on the upper-right corner of GitHub, then select **Your repositories**.
